# ==============================================================
# = Discovery Service Eureka Server
# = Dash: http://localhost:8761
# =============================================================

spring:
  application:
    name: eureka-server

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  
